### ISSUE TITLE
Enable and setup dependabot.yml configuration

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#20]
The goal of the task is to enable and configure Github dependabot to;

- Update npm dependencies.
- Update github actions/workflows

Here an example of a YML configuration:

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

> **Warning** the file must be created in the root `.github/` folder

> **Note** see the official [documentation](https://docs.github.com/fr/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) for more informations.

Here is an example with the PR for NodeSecure/CLI: https://github.com/NodeSecure/cli/pull/143

## List of repositories to update

The [AppSecurity](https://app.stepsecurity.io/) web app is doing all the work for us.

- [x] [CLI](https://github.com/NodeSecure/cli)
- [x] [scanner](https://github.com/NodeSecure/scanner)
- [x] [JS-X-Ray](https://github.com/NodeSecure/js-x-ray)
- [x] [i18n](https://github.com/NodeSecure/i18n)
- [x] [vulnera](https://github.com/NodeSecure/vulnera)
- [x] [CI](https://github.com/NodeSecure/ci)
- [x] [ci-action](https://github.com/NodeSecure/ci-action)
- [x] [RC](https://github.com/NodeSecure/rc)
- [x] [flags](https://github.com/NodeSecure/flags)
- [x] [report](https://github.com/NodeSecure/report)
- [x] [preview](https://github.com/NodeSecure/preview)
- [x] [domain-check](https://github.com/NodeSecure/Domain-check)
- [x] [estree-ast-utils](https://github.com/NodeSecure/estree-ast-utils)
- [x] [Utils](https://github.com/NodeSecure/Utils)
- [x] [fs-walk](https://github.com/NodeSecure/fs-walk)
- [x] [github](https://github.com/NodeSecure/github)
- [x] [gitlab](https://github.com/NodeSecure/gitlab)
- [x] [ossf-scorecard-sdk](https://github.com/NodeSecure/ossf-scorecard-sdk)
- [x] [npm-tarball-license-parser](https://github.com/NodeSecure/npm-tarball-license-parser)
- [x] [licenses-conformance](https://github.com/NodeSecure/licenses-conformance)
- [x] [size-satisfies](https://github.com/NodeSecure/size-satisfies)
- [x] [sec-literal](https://github.com/NodeSecure/sec-literal)
- [x] [vis-network](https://github.com/NodeSecure/vis-network)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config)
- [x] [npm-registry-sdk](https://github.com/NodeSecure/npm-registry-sdk)
- [x] [npm-security-fetcher](https://github.com/NodeSecure/npm-security-fetcher)
- [x] [documentation-ui](https://github.com/NodeSecure/documentation-ui)
- [x] [authors](https://github.com/NodeSecure/authors)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config)

> Feel free to help and open pull-request

**Comment by fraxken** [comment]
Note: https://app.stepsecurity.io/ is able to open pull request for us on the subject (testing it).

**Comment by fraxken** [comment]
If a `nsci` workflow is present, an update is also required

```yml
  nsci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - uses: NodeSecure/ci-action@v1
        with:
          warnings: warning
```
