### ISSUE TITLE
Update dependabot frequency

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#22]
The goal is to update the **frequency** parameter in all the dependabot configurations

> stored in`.github/dependabot.yml`

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    versioning-strategy: widen
    schedule:
      interval: weekly
```

New values are:
- **monthly** for github-actions
- **weekly** for npm

## To be updated

- [x] [CLI](https://github.com/NodeSecure/cli)
- [x] [scanner](https://github.com/NodeSecure/scanner)
- [x] [JS-X-Ray](https://github.com/NodeSecure/js-x-ray)
- [x] [i18n](https://github.com/NodeSecure/i18n)
- [x] [vulnera](https://github.com/NodeSecure/vulnera)
- [x] [CI](https://github.com/NodeSecure/ci)
- [x] [ci-action](https://github.com/NodeSecure/ci-action)
- [x] [RC](https://github.com/NodeSecure/rc)
- [x] [flags](https://github.com/NodeSecure/flags)
- [x] [report](https://github.com/NodeSecure/report)
- [x] [preview](https://github.com/NodeSecure/preview)
- [x] [domain-check](https://github.com/NodeSecure/Domain-check)
- [x] [estree-ast-utils](https://github.com/NodeSecure/estree-ast-utils)
- [x] [Utils](https://github.com/NodeSecure/Utils)
- [x] [fs-walk](https://github.com/NodeSecure/fs-walk)
- [x] [github](https://github.com/NodeSecure/github)
- [x] [gitlab](https://github.com/NodeSecure/gitlab)
- [x] [ossf-scorecard-sdk](https://github.com/NodeSecure/ossf-scorecard-sdk)
- [x] [npm-tarball-license-parser](https://github.com/NodeSecure/npm-tarball-license-parser)
- [x] [licenses-conformance](https://github.com/NodeSecure/licenses-conformance)
- [x] [size-satisfies](https://github.com/NodeSecure/size-satisfies)
- [x] [sec-literal](https://github.com/NodeSecure/sec-literal)
- [x] [vis-network](https://github.com/NodeSecure/vis-network)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config)
- [x] [npm-registry-sdk](https://github.com/NodeSecure/npm-registry-sdk)
- [x] [npm-security-fetcher](https://github.com/NodeSecure/npm-security-fetcher)
- [x] [documentation-ui](https://github.com/NodeSecure/documentation-ui)
- [x] [authors](https://github.com/NodeSecure/authors)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config)
