### ISSUE TITLE
Update CI to run tests on Windows & Mac

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/Governance#36]
We recently encountered a bug in `Scanner`, tests passes on Ubuntu & Mac but doesn't on Windows.
The idea is to run tests on theses 3 OS to prevent issues like that.

```yml
test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
```

Here is an example [PR](https://github.com/NodeSecure/cli/pull/192)
## Tools

- [x] [CLI](https://github.com/NodeSecure/cli)
- [ ] [scanner](https://github.com/NodeSecure/scanner)
- [ ] [RC](https://github.com/NodeSecure/rc)
- [ ] [report](https://github.com/NodeSecure/report)
- [ ] [fs-walk](https://github.com/NodeSecure/fs-walk)
